dist: trusty
language: node_js
node_js:
- "10.10.0"
cache:
  npm: true
  directories:
  - node_modules
install: npm install
before_script:
  - yarn lint
  - yarn build
  - yarn start --silent &
script:
  - yarn test
notifications:
  email: true
services:
  - mongodb
