dist: trusty
language: node_js
node_js:
- "10.10.0"
cache:
  directories:
  - node_modules
install: npm install
script:
  - yarn lint
  - yarn build
  - yarn start &
  - yarn test
notifications:
  email: true
services:
  - mongodb
